[package]
name = "axis-rt"
version = "0.1.0"
edition = "2021"
description = "A runtime for the Axis programming language."
authors = ["Raindrops", "ryze312"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
